version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - /Users/nsatybekov/docker/pg_data:/var/lib/postgresql/data
    networks:
      - local

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - local
  
  zookeeper:
    image: 'wurstmeister/zookeeper'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka'
    container_name: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    volumes:
      - /Users/nsatybekov/docker/kafka_data:/kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
  search:
    container_name: search
    image: elasticsearch:7.14.0
    restart: unless-stopped
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - /Users/nsatybekov/docker/search_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - http.max_content_length=1000mb
      - http.read_timeout=15m
    networks:
      - local
networks:
  local:
